### ISSUE TITLE
t2kdm-get Failures

### ISSUE THREAD

**Issue by hoganman** [t2k-software/t2kdm#23]
I try to download a MCP directory recursively

t2kdm-get -v /nd280/production006/L/mcp/neut/2015-08-air/magnet/run8/anal ./ -r

However, I get these messages

Getting /nd280/production006/L/mcp/neut/2015-08-air/magnet/run8/anal/oa_nt_beam_90820000-0000_vv3lthxfruqv_anal_000_magnet201508airrun8-bsdv01_2.root
Copying srm://t2ksrm.nd280.org/nd280data/production006/L/mcp/neut/2015-08-air/magnet/run8/anal/oa_nt_beam_90820000-0000_vv3lthxfruqv_anal_000_magnet201508airrun8-bsdv01_2.root to ./oa_nt_beam_90820000-0000_vv3lthxfruqv_anal_000_magnet201508airrun8-bsdv01_2.root
gfal-copy error: 70 (Communication error on send) - Could not stat the source: srm-ifce err: Communication error on send, err: [SE][Ls][] httpg://t2ksrm.nd280.org:8443/srm/managerv2: CGSI-gSOAP running on hep.colostate.edu reports Error initializing context
GSS Major Status: Authentication Failed

GSS Minor Status Error Chain:
globus_gsi_gssapi: SSL handshake problems
globus_gsi_gssapi: Unable to verify remote side's credentials
globus_gsi_gssapi: SSL handshake problems: Couldn't do ssl handshake
OpenSSL Error: s23_clnt.c:714: in library: SSL routines, function SSL23_GET_SERVER_HELLO

And these messages continue until I manually kill the process. 

I verified that t2kdm-test works too

[mhogan@hep run8-air]$ t2kdm-tests
Testing ls...
Testing replicas...
Testing exists...
Testing checksum...
Testing state...
Testing StorageElement...
Testing TriumfStorageElement...
Testing get...
Testing check...
Testing Commands...
Testing CLI...
All done.

**Comment by ast0815** [comment]
Does it work with gfal directly? Might be a grid problem rather than a t2kdm problem.

**Comment by hoganman** [comment]
As single file works

[mhogan@hep software]$ gfal-copy lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-air/magnet/run8/anal/oa_nt_beam_90820018-0003_j3powsqsnttd_anal_000_magnet201508airrun8-bsdv01_2.root /Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90820018-0003_j3powsqsnttd_anal_000_magnet201508airrun8-bsdv01_2.root
...
Copying lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-air/magnet/run8/anal/oa_nt_beam_90820018-0003_j3powsqsnttd_anal_000_magnet201508airrun8-bsdv01_2.root   [DONE]  after 24s

I tried a recursive copy and it worked

Copying 184191968 bytes lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314449915] BOTH   GFAL2:CORE:COPY	LIST:ENTER	
event: [1540314449915] BOTH   GFAL2:CORE:COPY	LIST:ITEM	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314449916] BOTH   GFAL2:CORE:COPY	LIST:EXIT	
event: [1540314449916] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:ENTER	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314449916] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:TYPE	streamed
monitor: lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root 6291456 6291456 37748736 6
monitor: lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root 10835285 15379114 130023424 12
event: [1540314471407] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:EXIT	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0000_bwdwcfvbd52a_anal_000_magnet201508waterrun8-bsdv01_2.root
Copying 183625259 bytes lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314472375] BOTH   GFAL2:CORE:COPY	LIST:ENTER	
event: [1540314472375] BOTH   GFAL2:CORE:COPY	LIST:ITEM	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314472375] BOTH   GFAL2:CORE:COPY	LIST:EXIT	
event: [1540314472375] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:ENTER	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314472375] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:TYPE	streamed
monitor: lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root 4893354 4893354 29360128 6
monitor: lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root 8039082 11184810 96468992 12
event: [1540314494513] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:EXIT	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0001_lm4dc2ucq462_anal_000_magnet201508waterrun8-bsdv01_2.root
Copying 181145344 bytes lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314495472] BOTH   GFAL2:CORE:COPY	LIST:ENTER	
event: [1540314495472] BOTH   GFAL2:CORE:COPY	LIST:ITEM	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314495472] BOTH   GFAL2:CORE:COPY	LIST:EXIT	
event: [1540314495473] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:ENTER	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314495473] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:TYPE	streamed
monitor: lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root 4194304 4194304 25165824 6
monitor: lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root 12582912 20971520 150994944 12
event: [1540314519381] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:EXIT	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0002_umzfm4d3vmsr_anal_000_magnet201508waterrun8-bsdv01_2.root
Copying 184014046 bytes lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0003_g2e5l2wfxe5p_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0003_g2e5l2wfxe5p_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314520380] BOTH   GFAL2:CORE:COPY	LIST:ENTER	
event: [1540314520381] BOTH   GFAL2:CORE:COPY	LIST:ITEM	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0003_g2e5l2wfxe5p_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0003_g2e5l2wfxe5p_anal_000_magnet201508waterrun8-bsdv01_2.root
event: [1540314520381] BOTH   GFAL2:CORE:COPY	LIST:EXIT	
event: [1540314520381] BOTH   GFAL2:CORE:COPY:LOCAL	TRANSFER:ENTER	lfn:/grid/t2k.org/nd280/production006/L/mcp/neut/2015-08-water/magnet/run8/anal/oa_nt_beam_90830000-0003_g2e5l2wfxe5p_anal_000_magnet201508waterrun8-bsdv01_2.root => file:///Raid/t2k/production006/mcp6_Spin_L/neut/run8-water/oa_nt_beam_90830000-0003_g2e5l2wfxe5p_anal_000_magnet201508waterrun8-bsdv01_2.root

**Comment by ast0815** [comment]
I just tried to download the files you specified originally from TRIUMF using t2kdm and it worked flawlessly. I agree that all of these problems were probably temporary grid issues. Unfortunately these seem to be quite common.

As general advice: If something does not work in the future, try the same thing with "stock" software like gfal. But do it timely, because these issues tend to be transient. If it also does not work with gfal, then it is a grid issue and you can open a ticket on GGUS: https://ggus.eu/?mode=ticket_submit
