### ISSUE TITLE
Unclear description of location.

### ISSUE THREAD

**Issue by batkiewicz** [t2k-software/t2kdm#32]
It is not clear if my location should be one of SE locations and what should be the name of my `site` if this is not one from t2kdm-SEs list.

Proposed description:
---
What is your location?
It must follow the general pattern of '/continent/country/site'.
This is used to determine the closest storage element (SE) when downloading files.
Examples: /europe/uk/ral
          /americas/ca/triumf
          /asia/jp/kek
You can see the locations of all available SEs by running `t2kdm-SEs`.
If your location is not one of the SEs and you don't know the name of your `site`,
you can use whatever name for the `site`. t2kdm will check how many levels
of your location are the same to judge how far away is each SE.

**Comment by ast0815** [comment]
Fixed in the newest release!
