### ISSUE TITLE
t2kdm-get -l option for saving a list of failed files not working

### ISSUE THREAD

**Issue by batkiewicz** [t2k-software/t2kdm#33]
I've run t2kdm-get with -l option:
`t2kdm-get /nd280/path/to/file/file.root ./anal/ -l ./download_failed.txt -v`

`./download_failed.txt` is empty although several files were not downloaded due to the following errors/warnings printed in the terminal:

`WARNING: Replica only found on tape, but tape sources are not accepted!
Could not find valid storage element with replica of /nd280/production007/A/mcp/anti-neut/2015-08-water/magnet/run7/anal/oa_nt_beam_80730251-0031_s4rvpvutqntt_anal_000_nu-bsdv01_2.root.`

`Copying srm://se03.esc.qmul.ac.uk:8444/srm/managerv2?SFN=/t2k.org/t2k.org/nd280/production007/A/mcp/anti-neut/2015-08-water/magnet/run7/anal/oa_nt_beam_80730293-0023_6jaya4t7y3hk_anal_000_nu-bsdv01_2.root to ./anal/oa_nt_beam_80730293-0023_6jaya4t7y3hk_anal_000_nu-bsdv01_2.root
...........
Copying srm://se03.esc.qmul.ac.uk:8444/srm/managerv2?SFN=/t2k.org/t2k.org/nd280/production007/A/mcp/anti-neut/2015-08-water/magnet/run7/anal/oa_nt_beam_80730293-0023_6jaya4t7y3hk_anal_000_nu-bsdv01_2.root   [FAILED]  after 3s
gfal-copy error: 70 (Communication error on send) - SOURCE CHECKSUM globus_ftp_client: the server responded with an error 500 error: commands denied`

**Comment by ast0815** [comment]
The `-l` option only works with the `-r` or `-R` options. Did you use those or did you write your own loop over the files?

**Comment by batkiewicz** [comment]
I've just realized that I'm running `t2kdm-get` in a loop:

`while read in`
`do`
`  t2kdm-get "$in" ./anal/ -l ./download_failed.txt -v >> download_output.txt 2>&1`
`done < missing_files_with_path.txt`

so `./download_failed.txt` may be overwritten each time. Nevertheless, the last download also failed with `copy error: 70 (Communication error on send)` error and the information about this fail is also not there.

**Comment by ast0815** [comment]
As I said, the `-l` option only works with the `-r` or `-R` options, i.e. when `t2kdm-get` is doing its own loop over the files (and possibly subdirectories). If you want to keep using your own loop, I suggest you check for the return value of `t2kdm-get`. E.g. something like this:

```
while read in
do
    t2kdm-get "$in" ./anal/ -v >>download_output.txt 2>&1
    if [[ $? -ne 0 ]]
    then
        echo "$in" >> ./download_failed.txt
    fi
done
```

**Comment by ast0815** [comment]
I just check the source. `-l` *should* work with a single file, but it is less robust than when used with `-r`. I will change the code so it will work the same for `-r` and without. It will still overwrite the file though. So for your own loop you will still have to check for the return value.

**Comment by batkiewicz** [comment]
Thanks!
I've checked what is written about it in `t2kdm-get --help`:
`  -l FILENAME, --list FILENAME`
`                        save a list of failed files to FILENAME`
If some argument is working under particular condition, it would be nice to write it in the usage instruction.

**Comment by ast0815** [comment]
Yeah. I'll also add some words that the file will be overwritten to the help text.
