### ISSUE TITLE
"t2kdm-tests" dies while "Testing get..."

### ISSUE THREAD

**Issue by JacekHoleczek** [t2k-software/t2kdm#43]
I am trying to use a remove batch cluster running:
CentOS Linux release 7.7.1908 (Core) / x86_64

I installed:
dirac_ui v7r1p29 (includes diracos v1r17)
t2kdm 1.12.1

The "t2kdm-tests" dies with an error:
```text
(... all fine here ...)
Testing get...
Traceback (most recent call last):
  File "/My/Private/dirac_ui_v7r1p29/diracos/usr/bin/t2kdm-tests", line 8, in <module>
    sys.exit(run_tests())
  File "/My/Private/dirac_ui_v7r1p29/diracos/usr/lib/python2.7/site-packages/t2kdm/tests.py", line 317, in run_tests
    run_read_only_tests(tape=args.tape)
  File "/My/Private/dirac_ui_v7r1p29/diracos/usr/lib/python2.7/site-packages/t2kdm/tests.py", line 160, in run_read_only_tests
    assert(dm.interactive.get(testdir, tempdir, recursive='test[12]\.txt', parallel=2) == 0)
  File "/My/Private/dirac_ui_v7r1p29/diracos/usr/lib/python2.7/site-packages/t2kdm/interactive.py", line 84, in recursive_function
    for g, path in mapper(is_good, utils.remote_iter_recursively(remotepath, regex, se=recursive_se, ignore_exceptions=True)):
  File "/My/Private/dirac_ui_v7r1p29/diracos/usr/lib/python2.7/site-packages/multiprocess/pool.py", line 673, in next
    raise value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

Such errors do not appear on a more local machine which runs a similar CentOS 7.9.2009 / x86_64, so it seems to be something specific to the remote machine but I have no idea how to "debug" it.

**Comment by ast0815** [comment]
The problem seems to be the parallelisation. Can you try and see whether `dill` is installed on the machine where this fails? I.e. in the DIRAC Python environment do `pip install dill`. Then try again.

If you do not use the parallel feature of `t2kdm`, you might just be able to ignore this error.

**Comment by JacekHoleczek** [comment]
So, the "dirac_ui" on both systems provides python 2.7.13, and in both cases, I can "import dill" (there is no "dill" for the default system provided python 2.7.5).

**Comment by ast0815** [comment]
Strange. Is the remote batch cluster maybe configured so you cannot spawn parallel processes? Don't really know what else it could be.

**Comment by JacekHoleczek** [comment]
I guess I found a possible problem comparing the list of files in "`./diracos/usr/lib/python2.7/site-packages/`" and "`./diracos/usr/lib64/python2.7/site-packages/`". There is one difference between both machines.
On both machines "t2kdm" installed "`multiprocess-0.70.11.1`" but on the remote batch machine into "`lib`" while on the local machine into `lib64`.

**Comment by ast0815** [comment]
That sounds like something similar to this issue here: https://github.com/uqfoundation/pathos/issues/134

Not sure there is much you can do about that, except asking your admins to provide a more complete build environment? Though I do not know what is actually missing.

**Comment by ast0815** [comment]
Actually it might just be the `python-devel` package.

**Comment by JacekHoleczek** [comment]
Indeed, the remote batch machine is missing this package.
My local machine has "`python-devel-2.7.5`" (well, the "dirac_ui" uses python 2.7.13, but fortunately, the old package seems to be fine),

**Comment by JacekHoleczek** [comment]
Knowing that I cannot have "multiprocess" properly built.
Is there any way to notify the "t2kdm" install procedure to skip it?
Is there any way to notify the "t2kdm-tests" utility to skip "parallelization" tests (but it should still test everything else without dying)?

**Comment by ast0815** [comment]
I just released v1.13.1 to add the `-p` argument, so you can set the maximum number of parallel processes in the tests. You can try setting that to 0 and see whether it works.

**Comment by JacekHoleczek** [comment]
Many thanks, "`t2kdm-tests -p 0`" works fine (well, at least no error is reported).

**Comment by ast0815** [comment]
The difference between `multiprocess` and `multiprocessing` is that the former uses `dill` for serialisation and the latter uses `pickle`. And `dill` is necessary to serialise functions and certain objects. When you use `multiprocessing` you get exactly the error you described in the beginning of this issue. tl;dr: `multiprocess` is more flexible than `multiprocessing`.

Closing, since it works now.
