### ISSUE TITLE
Wrong python_requires in setup.py

### ISSUE THREAD

**Issue by davehadley** [t2k-software/t2kdm#55]
I ran into confusing errors running `t2kdm`. The problem turned out to be because I was accidentally using a `python3` virtual environment. I guess that only `python2` is supported since `DIRAC` requires that.

To reproduce:

```bash
#!/usr/bin/env bash

python3 -m venv venv \
   && source venv/bin/activate \
   && pip install --upgrade pip \
   && pip install t2kdm \
   && t2kdm-get --help
```

produces the error:

```shell
Traceback (most recent call last):
  File "/home/epp/phskaj/scratch/venv/bin/t2kdm-get", line 5, in <module>
    from t2kdm.commands import get
  File "/home/epp/phskaj/scratch/venv/lib64/python3.6/site-packages/t2kdm/__init__.py", line 7, in <module>
    import configuration
ModuleNotFoundError: No module named 'configuration'
```
Apparently, in `python3` implicit relative import is not allowed.

The line: <https://github.com/t2k-software/t2kdm/blob/51ee08600ce3b631a90ce43f4edcc2f288d3859e/setup.py#L30>

could be changed to:
```
python_requires=">=2.6,<3.0"
```
I think that then `pip` would then refuse to install `t2kdm` giving the user a helpful error message that `python3` is not supported.

If the intention is to actually support `python3` then I think that these `import` statements need to be replaced with `import t2kdm.module` or `import .module`.

**Comment by guiguem** [comment]
Hey Dave, which branch are you using? There is a feature branch with python 3 support in the pull request. With this one you should be able to install t2kdm I think...

**Comment by davehadley** [comment]
I was using the version from pypi (<https://pypi.org/project/t2kdm/>).

Sorry, I didn't see your pull request (#53). Yes, it looks like when that is merged in that will solve this issue.

**Comment by ast0815** [comment]
Hi Dave,

there is only one issue with the error return code handling that's preventing the merge in the other branch. When that is sorted, we will merge it. Until then feel free to install the GitHub branch directly to test it. It should work. You can even install directly with `pip`: https://stackoverflow.com/questions/41491790/install-package-with-pip-from-specific-branch-of-github

**Comment by davehadley** [comment]
For completeness, the temporary workaround is to directly install from the work-in-progress branch [guiguem/python3](https://github.com/guiguem/t2kdm/tree/feature/python3):
```bash
pip install "git+https://github.com/guiguem/t2kdm@feature/python3"
```
